albia:
    email:
        sender:
            port: 587
            debug: true
            host: smtp.gmail.com
            username: robocarlos100@gmail.com
            password: wdekhppyaqlwvezc
            protocol: smtp
            defaultEncoding: UTF-8
            properties:
                mail:
                    smtp:
                        auth: true
                        starttls:
                            enable: true
                        socketFactory:
                            port: 465
                            class: javax.net.ssl.SSLSocketFactory
                            fallback: false
                        ssl:
                            enable: flase